modLoader="javafml"
loaderVersion="[45,)"
license="BSD-3-Clause"

[[mods]]
modId="slide_show"
version="${file.jarVersion}"
displayName="Slide Show"
authors="TeaConMC, BloCamLimb, 3TUSK, ustc-zzzz"
description="Minecraft mod, adding a projector that can display online images."

[[dependencies.slideshow]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.slideshow]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

